
[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[env]
TERM = "xterm-256color"
working_directory = "~/Code"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["new-session", "-D", '-f "$HOME/.tmux.conf"']
program = "/opt/homebrew/bin/tmux"

[window]
opacity = 0.9
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[terminal]
